name: Run Type and Format Checks

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  typecheck-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: "pnpm"

      - name: Type check
        run: pnpm typecheck

      - name: Format check
        run: pnpm format:check
